@api = http://localhost:60879/usuarios

GET {{api}}

###
POST {{api}}/add
Content-Type: application/json

{
    "usuario": "Elwey", 
    "correo": "josue@gmail.com", 
    "password": "sxaknak12"

}

###
DELETE {{api}}/Elwey

###
GET {{api}}/cuickcc6


###
POST {{api}}/verificacion
Content-Type: application/json

{
    "user": "Elwey", 
    "email": "josue@gmail.com", 
    "passW": "sxaknak12"

}
