@api = https://pasatareasappservicepia.azurewebsites.net

GET {{api}}/Jahir08

###
POST {{api}}
Content-Type: application/json

{
    "usuario": "Elwey", 
    "correo": "josue@gmail.com", 
    "password": "sxaknak12"

}

###
DELETE {{api}}/El papu
